t431_createTable=function(recid,tablehead,tabledata,tablecolsize,hastargetblank,btnstyles,t431__tdstyles,t431__thstyles,t431__oddrowstyles,t431__evenrowstyles){var t431__arrayColSize=t431_parseData(tablecolsize);var t431__arrayHead=t431_parseData(tablehead);var t431__arrayData=t431_parseData(tabledata);var t431__maxcolnumber=t431__findMaxRowLengthInTable(t431__arrayHead,t431__arrayData);var t431__colWidth=t431__setColumnsWidth(t431__arrayColSize,t431__maxcolnumber,recid);if(t431__colWidth[0].myText&&t431__colWidth[0].myText[t431__colWidth[0].myText.length-1]=="%"){for(var i=0;i<t431__colWidth.length;i++){t431__colWidth[i].myText=t431__colWidth[i].myText.slice(0,-1);t431__colWidth[i].myText+="vw"}}
var t431__container=$('#rec'+recid+' .t431 .t-container .t431__table');var t431__htmlTable="";if(t431__arrayHead){t431__htmlTable+=t431__generateHtml(recid,t431__arrayHead,"th",hastargetblank,t431__colWidth,btnstyles,t431__thstyles,null,null,t431__maxcolnumber)}
t431__container.append(t431__htmlTable);t431__htmlTable="";if(t431__arrayData){t431__htmlTable+=t431__generateHtml(recid,t431__arrayData,"td",hastargetblank,t431__colWidth,btnstyles,t431__tdstyles,t431__oddrowstyles,t431__evenrowstyles,t431__maxcolnumber)}
t431__container.append(t431__htmlTable)};t431_setHeadWidth=function(recid){if($(window).width()>960){var t431__tbody=$('#rec'+recid+' .t431 .t431__tbody');var t431__thead=$('#rec'+recid+' .t431 .t431__thead');t431__tbody.css("display","block");t431__thead.css("display","block");var t431__colWidth=$('#rec'+recid+' .t431 .t431__tbody tr:first').children().map(function(){return $(this).width()});if($('#rec'+recid+' .t431 .t431__tbody tr td:first').css('border-left-width').length>=3){var t431__verticalborder=$('#rec'+recid+' .t431 .t431__tbody tr td:first').css('border-left-width').slice(0,-2)}
$('#rec'+recid+' .t431 .t431__thead tr').children().each(function(i,v){if($(v).is(":last-child")){$(v).width(t431__colWidth[i]+(t431__tbody.width()-$('#rec'+recid+' .t431 .t431__tbody tr:first').width()))}else{$(v).width(t431__colWidth[i]+(+t431__verticalborder))}})}};t431__findMaxRowLengthInTable=function(arrayhead,arraydata){var t431__headmaxlength=0;var t431__datamaxlength=0;if(arrayhead){t431__headmaxlength=t431__findMaxRowLengInArray(arrayhead)}
if(arraydata){t431__datamaxlength=t431__findMaxRowLengInArray(arraydata)}
if(t431__datamaxlength>t431__headmaxlength){return t431__datamaxlength}else{return t431__headmaxlength}};t431__findMaxRowLengInArray=function(curarray){var t431__maxlength=0;for(var i=0;i<curarray.length;i++){if(curarray[i].length>t431__maxlength){t431__maxlength=curarray[i].length}}
return t431__maxlength};t431__setColumnsWidth=function(t431__colwidth,t431__colsnumber,recid){if(t431__colwidth){return t431__colwidth[0]}else{var t431__tablewidth=$('#rec'+recid+' .t431 .t-container .t-col').width();return(t431__tablewidth/t431__colsnumber+"px")}};t431__generateHtml=function(recid,arrayValues,coltag,hastargetblank,colWidth,btnstyles,colstyles,oddrowstyles,evenrowstyles,maxcolnumber){var t431__htmlpart="";if(coltag=="td"){var t431__theadorbodytag="tbody"}else{var t431__theadorbodytag="thead"}
t431__htmlpart+="<"+t431__theadorbodytag+" class=\"t431__"+t431__theadorbodytag+"\">";if($('#rec'+recid+' .t431 .t-container .t431__thead th').length>0&&$('#rec'+recid+' .t431 .t-container .t431__thead th').css("border-bottom-width")[0]!="0"){var t431__firstbodyrowstyle="border-top: 0 !important;"}
for(var i=0;i<arrayValues.length;i++){if(coltag=="td"){if((i+1)%2>0){t431__htmlpart+="<tr class=\"t431__oddrow\""+"style=\""+oddrowstyles+"\">"}else{t431__htmlpart+="<tr class=\"t431__evenrow\""+"style=\""+evenrowstyles+"\">"}}else{t431__htmlpart+="<tr>"}
var t431__addingcols=0;if(arrayValues[i].length<maxcolnumber){t431__addingcols=maxcolnumber-arrayValues[i].length}
for(var j=0;j<(arrayValues[i].length+t431__addingcols);j++){if(arrayValues[i][j]){if(Array.isArray(colWidth)&&colWidth[j]){var t431__curWidth=colWidth[j].myText}else{var t431__curWidth=colWidth}
if(i==0&&coltag=="td"){var t431__colwithattr="<"+coltag+" class=\"t431__"+coltag+"\" style=\"width:"+t431__curWidth+";"+colstyles+t431__firstbodyrowstyle+"\">"}else{var t431__colwithattr="<"+coltag+" class=\"t431__"+coltag+"\" style=\"width:"+t431__curWidth+";"+colstyles+"\">"}
if(arrayValues[i][j].myHref){var t431__tblank="";if(hastargetblank){var t431__tblank="target=\"_blank\""}
if(arrayValues[i][j].myHrefType=="link"){var t431__linkwithattr="<a href=\""+arrayValues[i][j].myHref+"\""+t431__tblank+">";var t431__linkclosetag="</a>"}else{var t431__linkwithattr="<div class=\"t431__btnwrapper\"><a href=\""+arrayValues[i][j].myHref+"\""+t431__tblank+" class=\"t-btn t-btn_sm\" style=\""+btnstyles+"\"><table style=\"width:100%; height:100%;\"><tr><td>";var t431__linkclosetag="</td></tr></table></a></div>"}
t431__htmlpart+=t431__colwithattr+t431__linkwithattr+arrayValues[i][j].myText+t431__linkclosetag+"</"+coltag+">"}else{t431__htmlpart+=t431__colwithattr+arrayValues[i][j].myText+"</"+coltag+">"}}else{t431__htmlpart+="<"+coltag+" class=\"t431__"+coltag+"\" style=\"width:"+t431__curWidth+";"+colstyles+"\">"+"</"+coltag+">"}}
t431__htmlpart+="</tr>"}
t431__htmlpart+="</"+t431__theadorbodytag+">";return t431__htmlpart};t431_parseData=function(t431__data){if(t431__data!=""&&typeof t431__data!='undefined')
{t431__data=t431__addBrTag(t431__data);var t431__arrayTable=new Array();var t431__arrayRow=new Array();var t431__curItem={myText:"",myHref:"",myHrefType:""};var t431__HasLink="";var t431__HasLinkWithSpace="";var t431__HasBtn="";var t431__HasBtnWithSpace="";var t431__EndOfLine="";for(var i=0;i<t431__data.length;i++)
{if(t431__data[i]==";"&&!((t431__data[i-1]&&(t431__data[i-1]=="t"))&&(t431__data[i-2]&&(t431__data[i-2]=="g"||t431__data[i-2]=="l"))&&(t431__data[i-3]&&(t431__data[i-3]=="&")))&&!((t431__data[i-1]&&(t431__data[i-1]=="p"))&&(t431__data[i-2]&&(t431__data[i-2]=="m"))&&(t431__data[i-3]&&(t431__data[i-3]=="a"))&&(t431__data[i-4]&&(t431__data[i-4]=="&")))){t431__arrayRow.push(t431__curItem);var t431__curItem={myText:"",myHref:""};t431__HasLink="";t431__HasLinkWithSpace="";t431__HasBtn="";t431__HasBtnWithSpace=""}else{if(t431__HasLink=="link="||t431__HasLinkWithSpace==" link="||t431__HasBtn=="button="||t431__HasBtnWithSpace==" button="){if(t431__curItem.myHref==""&&t431__HasLink=="link="){t431__curItem.myText=t431__curItem.myText.slice(0,-5);t431__curItem.myHrefType="link"}else{if(t431__curItem.myHref==""&&t431__HasLinkWithSpace==" link="){t431__curItem.myText=t431__curItem.myText.slice(0,-6);t431__curItem.myHrefType="link"}else{if(t431__curItem.myHref==""&&t431__HasBtn=="button="){t431__curItem.myText=t431__curItem.myText.slice(0,-7);t431__curItem.myHrefType="btn"}else{if(t431__curItem.myHref==""&&t431__HasBtnWithSpace==" button="){t431__curItem.myText=t431__curItem.myText.slice(0,-8);t431__curItem.myHrefType="btn"}}}}
t431__curItem.myHref+=(t431__data[i])}else{t431__curItem.myText+=(t431__data[i]);t431__HasLink=t431__checkSubstr("link=",t431__HasLink,t431__data[i]);t431__HasLinkWithSpace=t431__checkSubstr(" link=",t431__HasLinkWithSpace,t431__data[i]);t431__HasBtn=t431__checkSubstr("button=",t431__HasBtn,t431__data[i]);t431__HasBtnWithSpace=t431__checkSubstr(" button=",t431__HasBtnWithSpace,t431__data[i])}
t431__EndOfLine=t431__checkSubstr("<br />",t431__EndOfLine,t431__data[i]);if(t431__EndOfLine=="<br />"){if(t431__curItem.myHref){t431__curItem.myHref=t431__curItem.myHref.slice(0,-6)}else{t431__curItem.myText=t431__curItem.myText.slice(0,-6)}
t431__arrayRow.push(t431__curItem);t431__arrayTable.push(t431__arrayRow);var t431__curItem={myText:"",myHref:""};t431__HasLink="";t431__HasLinkWithSpace="";t431__HasBtn="";t431__HasBtnWithSpace="";t431__arrayRow=new Array()}}}
if(t431__arrayRow.length>0||t431__curItem.myText!=""){if(t431__curItem!=""){t431__arrayRow.push(t431__curItem)}
t431__arrayTable.push(t431__arrayRow)}}
return t431__arrayTable};t431__checkSubstr=function(t431__targetSubstr,t431__curSubstr,t431__curSymbol){if(!t431__curSubstr&&t431__curSymbol==t431__targetSubstr[0]){return t431__curSymbol}else{if(t431__curSubstr){for(var i=0;i<(t431__targetSubstr.length-1);i++){if(t431__curSubstr[t431__curSubstr.length-1]==t431__targetSubstr[i]&&t431__curSymbol==t431__targetSubstr[i+1]){return(t431__curSubstr+=t431__curSymbol)}}}}};t431__addBrTag=function(t431__oldStringItem){if(typeof t431__oldStringItem=='undefined')return;var t431__newStringItem="";for(var i=0;i<t431__oldStringItem.length;i++){if(t431__oldStringItem[i]=="\n"||t431__oldStringItem[i]=="\r"){t431__newStringItem+="<br />"}else{t431__newStringItem+=t431__oldStringItem[i]}}
return t431__newStringItem};function t552_init(recid,ratio){var t552__el=$("#rec"+recid),t552__image=t552__el.find(".t552__blockimg:first");t552__setHeight(recid,t552__image,ratio);var t552__doResize;$(window).resize(function(){clearTimeout(t552__doResize);t552__doResize=setTimeout(function(){t552__setHeight(recid,t552__image,ratio)},200)})}
function t552__setHeight(recid,image,ratio){$("#rec"+recid+" .t552__blockimg").css("height",Math.round(image.innerWidth()*ratio))}
function t774_init(recid){t774_unifyHeights(recid);$(window).bind('resize',t_throttle(function(){t774_unifyHeights(recid)},200));$(".t774").bind("displayChanged",function(){t774_unifyHeights(recid)});$(window).load(function(){t774_unifyHeights(recid)})}
function t774_unifyHeights(recid){var t774_el=$('#rec'+recid),t774_blocksPerRow=t774_el.find(".t774__container").attr("data-blocks-per-row"),t774_cols=t774_el.find(".t774__content"),t774_mobScroll=t774_el.find(".t774__scroll-icon-wrapper").length;if($(window).width()<=480&&t774_mobScroll==0){t774_cols.css("height","auto");return}
var t774_perRow=+t774_blocksPerRow;if($(window).width()<=960&&t774_mobScroll>0){var t774_perRow=t774_cols.length}
else{if($(window).width()<=960){var t774_perRow=2}}
for(var i=0;i<t774_cols.length;i+=t774_perRow){var t774_maxHeight=0,t774_row=t774_cols.slice(i,i+t774_perRow);t774_row.each(function(){var t774_curText=$(this).find(".t774__textwrapper"),t774_curBtns=$(this).find(".t774__btn-wrapper, .t774__btntext-wrapper"),t774_itemHeight=t774_curText.outerHeight()+t774_curBtns.outerHeight();if(t774_itemHeight>t774_maxHeight){t774_maxHeight=t774_itemHeight}});t774_row.css("height",t774_maxHeight)}}
function t821_init(recid){var rec=$('#rec'+recid);var el=rec.find('.t821');var isFixed=(el.css('position')=='fixed');var redactorMode=el.hasClass('t821_redactor-mode');if(!redactorMode){el.removeClass('t821__beforeready');if(isFixed&&el.attr('data-bgopacity-two')){t821_changebgopacitymenu(recid);$(window).bind('scroll',t_throttle(function(){t821_changebgopacitymenu(recid)},200))}
if(isFixed&&el.attr('data-appearoffset')){el.removeClass('t821__beforeready');t821_appearMenu(recid);$(window).bind('scroll',t_throttle(function(){t821_appearMenu(recid)},200))}}
t821_setBg(recid);$(window).bind('resize',t_throttle(function(){t821_setBg(recid)},200))}
function t821_setBg(recid){var window_width=$(window).width();if(window_width>980){$(".t821").each(function(){var el=$(this);if(el.attr('data-bgcolor-setbyscript')=="yes"){var bgcolor=el.attr("data-bgcolor-rgba");el.css("background-color",bgcolor)}})}else{$(".t821").each(function(){var el=$(this);var bgcolor=el.attr("data-bgcolor-hex");el.css("background-color",bgcolor);el.attr("data-bgcolor-setbyscript","yes")})}}
function t821_appearMenu(recid){var window_width=$(window).width();if(window_width>980){$(".t821").each(function(){var el=$(this);var appearoffset=el.attr("data-appearoffset");if(appearoffset!=""){if(appearoffset.indexOf('vh')>-1){appearoffset=Math.floor((window.innerHeight*(parseInt(appearoffset)/100)))}
appearoffset=parseInt(appearoffset,10);if($(window).scrollTop()>=appearoffset){if(el.css('visibility')=='hidden'){el.finish();el.css("top","-50px");el.css("visibility","visible");el.animate({"opacity":"1","top":"0px"},200,function(){})}}else{el.stop();el.css("visibility","hidden")}}})}}
function t821_changebgopacitymenu(recid){var window_width=$(window).width();if(window_width>980){$(".t821").each(function(){var el=$(this);var bgcolor=el.attr("data-bgcolor-rgba");var bgcolor_afterscroll=el.attr("data-bgcolor-rgba-afterscroll");var bgopacityone=el.attr("data-bgopacity");var bgopacitytwo=el.attr("data-bgopacity-two");var menushadow=el.attr("data-menushadow");if(menushadow=='100'){var menushadowvalue=menushadow}else{var menushadowvalue='0.'+menushadow}
if($(window).scrollTop()>20){el.css("background-color",bgcolor_afterscroll);if(bgopacitytwo=='0'||menushadow==' '){el.css("box-shadow","none")}else{el.css("box-shadow","0px 1px 3px rgba(0,0,0,"+menushadowvalue+")")}}else{el.css("background-color",bgcolor);if(bgopacityone=='0.0'||menushadow==' '){el.css("box-shadow","none")}else{el.css("box-shadow","0px 1px 3px rgba(0,0,0,"+menushadowvalue+")")}}})}}
function t821_createMobileMenu(recid){var window_width=$(window).width(),el=$("#rec"+recid),menu=el.find(".t821"),burger=el.find(".t821__mobile");burger.click(function(e){menu.fadeToggle(300);$(this).toggleClass("t821_opened")})
$(window).bind('resize',t_throttle(function(){window_width=$(window).width();if(window_width>980){menu.fadeIn(0)}},200))}
function t823_onSuccess(form){var inputsWrapper=form.find('.t-form__inputsbox');var inputsHeight=inputsWrapper.height();var inputsOffset=inputsWrapper.offset().top;var inputsBottom=inputsHeight+inputsOffset;var targetOffset=form.find('.t-form__successbox').offset().top;if($(window).width()>960){var target=targetOffset-200}else{var target=targetOffset-100}
if(targetOffset>$(window).scrollTop()||($(document).height()-inputsBottom)<($(window).height()-100)){inputsWrapper.addClass('t823__inputsbox_hidden');setTimeout(function(){if($(window).height()>$('.t-body').height()){$('.t-tildalabel').animate({opacity:0},50)}},300)}else{$('html, body').animate({scrollTop:target},400);setTimeout(function(){inputsWrapper.addClass('t823__inputsbox_hidden')},400)}
var successurl=form.data('success-url');if(successurl&&successurl.length>0){setTimeout(function(){window.location.href=successurl},500)}}